heat_template_version: 2014-10-16

description: This is a autoscaling template

resources:
  group:
    type: OS::Heat::AutoScalingGroup
    properties:
       cooldown: 10
       desired_capacity: 1
       max_size: 2
       min_size: 1
       resource:
         type: OS::Nova::Server::server1 

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group }
      cooldown: 10
      scaling_adjustment: 1

  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group }
      cooldown: 10
      scaling_adjustment: -1

  cpu_alarm_high:
     type: OS::Ceilometer::Alarm
     properties:
       description: Scale up resources if the cpu average utlization is greater then 50 for 1 minute or more
       meter_name: cpu_util
       statistic: avg
       period: 10
       evaluation_periods: 1
       threshold: 40
       alarm_actions:
         - {get_attr: [scaleup_policy, alarm_url]}
       comparison_operator: gt

  cpu_alarm_low:
     type: OS::Ceilometer::Alarm
     properties:
       description: Scale down resources if the cpu average utlization is less then 10 for 1 minute or more
       meter_name: cpu_util
       statistic: avg
       period: 10
       evaluation_periods: 1
       threshold: 20
       alarm_actions:
         - {get_attr: [scaledown_policy, alarm_url]}
       comparison_operator: lt
